version: '3.8'

services:
  gitea-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.kuiper.com/gitea-assistant:latest
    container_name: gitea-assistant
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 512M
